type add missing `/` Update plugin.py
needed to counter:

FileNotFoundError: [Errno 2] No such file or directory: 'usr/lib/python3.8/site-packages/ckanext/berlin_dataset_schema/public/licenses/berlin-od-portal.json'